### ISSUE TITLE
Is the mask image of the gallery and probe a complete step?

### ISSUE THREAD

**Issue by updatelse** [ShiqiYu/OpenGait#163]
I have a question based on mask image for gait recognition, which is whether the proposed mask has the periodicity of human gait? If the mask graph in the gallery is not a complete gait cycle, and the mask in the probe is not a complete stride. These two steps are not a complete gait, so how do they compare and recognize?

Have they been aligned? If so, I didn't find where the alignment was done in the code.

**Comment by ChaoFan996** [comment]
Good question!
As far as my knowledge, there should be only a few gait works talking about this issue, i.e., should we align the frames between the gallery and probe in a frame-by-frame manner?
Generally, the temporal pooling module is considered able to produce a global understanding of the entire gait sequence. 
That is to say, now the gait metric learning is based on sequence-level representations, rather than frame-level ones. 
Maybe we can advance to frame-level learning, which can be regarded as a more fine-grained way of learning gait features in the future. 
Any solutions are welcome!
