### ISSUE TITLE
SUSTech1K数据集问题

### ISSUE THREAD

**Issue by Lxzzzzzzzzzzz** [ShiqiYu/OpenGait#255]
想请问一下数据集中的的sils_raw和sils_aligned图片分别是怎样对rgb图片处理得到的，处理方式有何不同

**Comment by jdyjjj** [comment]
Sils_aligned is the result of data preprocessing using the pretreatment.py

**Comment by chuanfushen** [comment]
> 想请问一下数据集中的的sils_raw和sils_aligned图片分别是怎样对rgb图片处理得到的，处理方式有何不同

sils_raw is obtained by applying foreground segmentation on the RGB_raw images. Since RGB_raw images are the results from detection methods, the segmented sils_raw are with black pixel at both up and bottom regions.

sils_algined is the results by running pretreatment.py, meaning that the black pixels at top and bottom are removed to algin spatially.
