### ISSUE TITLE
what does the parallel_BN1d mean？

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#56]
https://github.com/ShiqiYu/OpenGait/blob/1be7333c8656223af8eab9c2bc81fd429dfd2f9c/opengait/modeling/modules.py#L128

**Comment by wj1tr0y** [comment]
since many models use horizontal pooling, the output vectors are separated into S parts. Each part would have a BN1D layer. But for faster implementation, parallel_BN1d uses one BN layer with the size of part_num*vector_channels. To be more specific, parallel_BN1d firstly flattens vectors into Nx(PxC), then performs BN operation, and lastly reshapes the vector into PxNxC.
