### ISSUE TITLE
reproduce question on ou-mvlp

### ISSUE THREAD

**Issue by mollibottie333** [ShiqiYu/OpenGait#72]
## System information (version)

- Pytorch =>  1.8
- Operating System / Platform => linux
- Cuda => 11.4

## Detailed description
1. what's the definition of inference time in model_zoo? it takes me more than 30 minutes to test GaitGL on ou-mvlp dataset.
2. how many seqs are used to test the performance on ou-mvlp?  In my reproduction, there are 133478 seqs. I wonder if the seqs number is equal to your setting. 

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by noahshen98** [comment]
How many GPU card do you use to inference model?
We evaluate with eight GPU (RTX 6000).

I forgot exact sequence number for OUMVLP, but 133478 seems no problem for me. Since 5000 id * 14 view * 2 times is close to 140,000, which is closed to 133478.

So, there are two reasons： （1） GPU is short, or （2）IO bottleneck because dataset is stored in HDD.
